name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install apache2
          sudo apt-get install libapache2-mod-php
          sudo apt-get install php
          sudo apt-get install php-xml
          sudo apt-get install php-mbstring
          sudo apt-get install php-zip
          sudo apt-get install php-mysql
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      - name: Build assets
        run: |
          npm install
          npm run production
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/html
            sudo https://github.com/Srk7995/githubaction.git
            cd githubaction
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            sudo chown -R www-data:www-data storage/
            sudo chmod -R 755 storage/
            sudo chown -R www-data:www-data bootstrap/cache/
            sudo chmod -R 755 bootstrap/cache/
            php artisan migrate --force
